# Generated by Django 4.1.7 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_cleaning"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("M", "Maintenance"),
                            ("S", "Style"),
                            ("P", "Personal"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(name="cleaning", options={"ordering": ["-date"]},),
        migrations.AlterField(
            model_name="cleaning",
            name="date",
            field=models.DateField(verbose_name="cleaning date"),
        ),
        migrations.AddField(
            model_name="sneaker",
            name="customizations",
            field=models.ManyToManyField(to="main_app.customization"),
        ),
    ]
