# Generated by Django 4.1.7 on 2023-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_customization_alter_cleaning_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customization",
            name="type",
            field=models.CharField(
                choices=[("M", "Maintenance"), ("S", "Stylish"), ("P", "Personal")],
                max_length=1,
            ),
        ),
    ]
