# Generated by Django 4.1.7 on 2023-03-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_customization_type"),
    ]

    operations = [
        migrations.RenameModel(old_name="Customization", new_name="Customizations",),
    ]
