# Generated by Django 4.1.7 on 2023-03-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_rename_customization_customizations"),
    ]

    operations = [
        migrations.RenameModel(old_name="Customizations", new_name="Customization",),
    ]
